### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by petermorlion** [Sebazzz/EntityProfiler#3]
The readme mentions installing the nuget package, but I can't find it on nuget.org.

**Comment by Sebazzz** [comment]
No - you're right. There isn't a NuGet package right now.

This is because I'm not happy yet with the cross-process communication between EntityProfiler and the debuggee. The communication uses a fixed port number, so it would only allow profiling one instance of an app.

**Comment by petermorlion** [comment]
Ok cool.
